[package]
name = "suipump"
edition = "2024.beta"

[dependencies]
CetusClmm = { git = "https://github.com/CetusProtocol/cetus-clmm-interface.git", subdir = "sui/clmmpool", rev = "testnet-v1.23.1" }

[addresses]
suipump = "0x0"

[dev-dependencies]

[dev-addresses]

